---
version: 2

before:
  hooks:
    - "sh -c \"cd backend && go mod tidy\""
    - "sh -c \"cd frontend && pnpm install && pnpm build\""

builds:
  - dir: "./backend"
    main: "./cmd/server/"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "darwin"
      - "linux"
    goarch:
      - "amd64"
      - "arm64"
    tags:
      - "serveui"

# Container Image build
kos:
  - repository: "ghcr.io/meh-hackathon/meh"
    base_image: "alpine:3.22.1"
    tags:
      - "{{ .Version }}"
    bare: true
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
      - "linux/arm64"

release:
  draft: true
...
