---
version: 2

before:
  hooks:
    - "sh -c \"cd backend && go mod tidy\""

builds:
  - main: "./backend/cmd/server" 
    env:
      - "CGO_ENABLED=0"
    goos:
      - "darwin"
      - "linux"
    goarch:
      - "amd64"
      - "arm64"

# Container Image build
kos:
  - repository: "oci://ghcr.io/meh-hackathon/meh"
    base_image: "alpine:3.22.1"
    tags:
      - "{{ .Version }}"
    bare: true
    preserve_import_paths: false
    platforms:
      - "linux/amd64"
      - "linux/arm64"

release:
  draft: true
...
