---
version: "3"

tasks:
  install:
    cmds:
      - "brew install pre-commit go-task"

  lint:
    cmds:
      - "pre-commit run --all-files"

  test:
    cmds:
      - "go test -C backend ./... -tags=test"

  run:
    cmds:
      - "go run -C backend ./..."

  build:
    cmds:
      - "go build -C backend ./..."

  build-image:
    cmds:
      - "ko build --platform all --local"

  test-release-goreleaser:
    cmds:
      - "goreleaser release --snapshot --clean"

  test-github-actions:
    cmds:
      - "act"
...
