/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user
         * @description Get the current user information
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with username and password
         * @description Authenticate a user using username and password
         */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppError: {
            code: string;
            api_message?: string;
            /** Format: int32 */
            status_code: number;
            values?: {
                [key: string]: unknown;
            };
        };
        User: {
            /** @description User ID */
            id: string;
            /** @description Username of the user */
            username: string;
            /** @description Email address of the user */
            email?: string;
            roles?: components["schemas"]["Role"][];
            /** @description Additional metadata about the user */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        Role: "admin";
        PasswordGrantRequest: {
            /**
             * @description The grant type for password authentication
             * @enum {string}
             */
            grant_type: "password";
            /** @description Username of the user */
            username: string;
            /** @description Password of the user */
            password: string;
        };
        RefreshTokenGrantRequest: {
            /**
             * @description The grant type for refreshing the token
             * @enum {string}
             */
            grant_type: "refresh_token";
            /** @description The refresh token to use for obtaining a new access token */
            refresh_token: string;
        };
        TokenRequest: components["schemas"]["PasswordGrantRequest"] | components["schemas"]["RefreshTokenGrantRequest"];
        Token: {
            /** @description The access token for the user */
            access_token: string;
            /** @description The refresh token for the user */
            refresh_token: string;
            /** @description The number of seconds until the access token expires */
            expires_in: number;
            /** @description The type of the token (e.g., Bearer) */
            token_type: string;
        };
    };
    responses: {
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AppError"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AppError"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AppError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
